scp -P2222 ./html/css/bootstrap-theme.css user@localhost:/srv/http/css/bootstrap-theme.css 
scp -P2222 ./html/css/bootstrap-theme.css.map user@localhost:/srv/http/css/bootstrap-theme.css.map 
scp -P2222 ./html/css/bootstrap-theme.min.css user@localhost:/srv/http/css/bootstrap-theme.min.css 
scp -P2222 ./html/css/bootstrap.css user@localhost:/srv/http/css/bootstrap.css 
scp -P2222 ./html/css/bootstrap.css.map user@localhost:/srv/http/css/bootstrap.css.map 
scp -P2222 ./html/css/bootstrap.min.css user@localhost:/srv/http/css/bootstrap.min.css 
scp -P2222 ./html/db/ds_service.db user@localhost:/srv/http/db/ds_service.db 
scp -P2222 ./html/fonts/glyphicons-halflings-regular.eot user@localhost:/srv/http/fonts/glyphicons-halflings-regular.eot 
scp -P2222 ./html/fonts/glyphicons-halflings-regular.svg user@localhost:/srv/http/fonts/glyphicons-halflings-regular.svg 
scp -P2222 ./html/fonts/glyphicons-halflings-regular.ttf user@localhost:/srv/http/fonts/glyphicons-halflings-regular.ttf 
scp -P2222 ./html/fonts/glyphicons-halflings-regular.woff user@localhost:/srv/http/fonts/glyphicons-halflings-regular.woff 
scp -P2222 ./html/include/.admin.php user@localhost:/srv/http/include/.admin.php 
scp -P2222 ./html/include/functions.php user@localhost:/srv/http/include/functions.php 
scp -P2222 ./html/js/bootstrap.js user@localhost:/srv/http/js/bootstrap.js 
scp -P2222 ./html/js/bootstrap.min.js user@localhost:/srv/http/js/bootstrap.min.js 
scp -P2222 ./html/index.php user@localhost:/srv/http/index.php 
scp -P2222 ./html/dashboard.php user@localhost:/srv/http/dashboard.php 
scp -P2222 ./html/export.php user@localhost:/srv/http/export.php 
scp -P2222 ./html/login.php user@localhost:/srv/http/login.php 
scp -P2222 ./html/register.php user@localhost:/srv/http/register.php 
scp -P2222 ./html/sign.php user@localhost:/srv/http/sign.php 
scp -P2222 ./html/keys/.htaccess user@localhost:/srv/http/keys/.htaccess 
