scp -P2222 user@localhost:/srv/http/css/bootstrap-theme.css ./html/css/bootstrap-theme.css
scp -P2222 user@localhost:/srv/http/css/bootstrap-theme.css.map ./html/css/bootstrap-theme.css.map
scp -P2222 user@localhost:/srv/http/css/bootstrap-theme.min.css ./html/css/bootstrap-theme.min.css
scp -P2222 user@localhost:/srv/http/css/bootstrap.css ./html/css/bootstrap.css
scp -P2222 user@localhost:/srv/http/css/bootstrap.css.map ./html/css/bootstrap.css.map
scp -P2222 user@localhost:/srv/http/css/bootstrap.min.css ./html/css/bootstrap.min.css
scp -P2222 user@localhost:/srv/http/db/ds_service.db ./html/db/ds_service.db
scp -P2222 user@localhost:/srv/http/fonts/glyphicons-halflings-regular.eot ./html/fonts/glyphicons-halflings-regular.eot
scp -P2222 user@localhost:/srv/http/fonts/glyphicons-halflings-regular.svg ./html/fonts/glyphicons-halflings-regular.svg
scp -P2222 user@localhost:/srv/http/fonts/glyphicons-halflings-regular.ttf ./html/fonts/glyphicons-halflings-regular.ttf
scp -P2222 user@localhost:/srv/http/fonts/glyphicons-halflings-regular.woff ./html/fonts/glyphicons-halflings-regular.woff
scp -P2222 user@localhost:/srv/http/include/.admin.php ./html/include/.admin.php
scp -P2222 user@localhost:/srv/http/include/functions.php ./html/include/functions.php
scp -P2222 user@localhost:/srv/http/js/bootstrap.js ./html/js/bootstrap.js
scp -P2222 user@localhost:/srv/http/js/bootstrap.min.js ./html/js/bootstrap.min.js
scp -P2222 user@localhost:/srv/http/index.php ./html/index.php
scp -P2222 user@localhost:/srv/http/dashboard.php ./html/dashboard.php
scp -P2222 user@localhost:/srv/http/export.php ./html/export.php
scp -P2222 user@localhost:/srv/http/login.php ./html/login.php
scp -P2222 user@localhost:/srv/http/register.php ./html/register.php
scp -P2222 user@localhost:/srv/http/sign.php ./html/sign.php
scp -P2222 user@localhost:/srv/http/keys/.htaccess ./html/keys/.htaccess
